# This document stores page configurations for blog posts, such as titles and upload dates.

[pages.frame_of_mind]
title = "On today's frame of mind"
published = 2021-06-22T19:46:00

[pages.building_this_site]
title = "Building this site"
published = 2021-06-24T21:35:00

[pages.text_editors]
title = "Text editors"
published = 2021-07-03T23:26:00

[pages.dusk_wants]
title = "Dusk musings"
published = 2021-07-03T23:26:00