name: Build and deploy Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'kaylynn234/website'
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: kaylynn234/kaylynn.gay:latest
          cache-from: type=registry,ref=kaylynn234/kaylynn.gay:latest
          cache-to: type=inline
