name: Build and deploy Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'kaylynn234/website'
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/bake-action@v2.2.0
        with:
          push: true
          load: false
          files: docker-bake.hcl
          set: |
            website.cache-from=type=gha
            website.cache-to=type=gha,mode=max
